# Generated by Django 5.2.6 on 2026-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_img',
            field=models.ImageField(default='images/lain1.png', upload_to='images/'),
        ),
    ]
